### ISSUE TITLE
support for local storage?

### ISSUE THREAD

**Issue by ballPointPenguin** [johntitus/node-horseman#120] opened 2016-01-29 17:06 UTC
Is there a way to set localStorage items?
I tried
```
.evaluate(function() {
  localStorage.setItem('foo', 'bar');
})
```
but that does not _seem_ to be working.

**Comment by awlayton** [comment] 2016-01-29 17:51
[This website](http://dev-test.nemikor.com/web-storage/support-test/) says it supports `localStorage`. 
[Results](https://github.com/johntitus/node-horseman/files/110171/results.pdf)

**Comment by ballPointPenguin** [comment] 2016-01-29 18:11
Is the above 'evaluate' method the way to interact with localStorage then?
I am not sure if the localStorage method is available within the scope within the evaluate block. Would it maybe be window.localStorage?

**Comment by awlayton** [comment] 2016-01-29 18:17
I have never actually used local storage. I believe either `localStorage` or `window.localStorage` should work the same.

Could you clarify what you mean by "does not *seem* to be working"?

**Comment by ballPointPenguin** [comment] 2016-01-29 18:50
I'm using localStorage for some authentication parameters in my webapp.
In Firefox, for example, I can open the login page, run localStorage.setItem('foo', 'bar') from the console, refresh the page, and be authenticated. I am struggling to do the same thing with node-horseman.

If it is getting set, it must be getting lost. I have tried using various combinations of
.open(loginUrl)
.evaluate(/*set local storage*/)
.open(protectedUrl),

.open(protectedUrl)
.evaluate(function() {
 // set local storage
 window.location.reload();
}),

.open(protectedUrl)
.evaluate(/* set local storage */)
.reload()

**Comment by awlayton** [comment] 2016-01-29 19:27
Are you getting any errors from phantomjs? Be sure you have set an error handler with `horseman.on('error', ...)`.

**Comment by awlayton** [comment] 2016-03-11 01:28
Closing because I used `localStorage` and it worked fine for me. You can reopen this if you have more to post @ballPointPenguin (such as a script to reproduce the error).

**Closed by awlayton** 2016-03-11 01:28 UTC
