### ISSUE TITLE
How to wait for post request to be completed?

### ISSUE THREAD

**Issue by aldarund** [johntitus/node-horseman#235] opened 2016-10-31 19:42 UTC
How to wait for post request to be completed?
I have a page where  when a link click a post request issued and the content replaced with a new one. But its the same html structure ,e.g. same selectors so waitForSelector wont work.
Explicitly wait for x second doesnt sound good too, because  request can take anywhere from 1 sec to 10 second, and waiting 10 second for each request not good.
When i was writing similar script in casperjs it was waiting for such actions automatically.

**Comment by awlayton** [comment] 2016-10-31 19:54
Did you try `.waitForNextPage()`?

Are you sure CasperJS's click waits for it? I wonder how they do that...

**Comment by aldarund** [comment] 2016-10-31 20:45
waitForNextPage doesnt work, it just timeout. I was use it on different sites, although they work same way. 
Now tried it on same site.
Here is casperjs script.
```
var casper = require('casper').create();

casper.start('https://netforum.avectra.com/eweb/DynamicPage.aspx?Site=SLBOR&WebCode=IndResult&FromSearchControl=Yes');

function getListingAndWrite() {
    var nextPage = casper.evaluate(function () {
        return document.querySelectorAll("span.DataFormChildDataGridPagerLink+a")[0].text;
    });
    casper.echo(nextPage);
    casper.thenClick('span.DataFormChildDataGridPagerLink+a');
    casper.then(getListingAndWrite);
}

casper.then(getListingAndWrite);


casper.run();

```
casper.thenClick('span.DataFormChildDataGridPagerLink+a'); -> here casper wait for post to be actual made and nextPage always change to next one. So it print 2 3 4 5 6 etc..

Here is horseman script that do same.
```
var Horseman = require("node-horseman");

var horseman = new Horseman({timeout: 10000});


function getListingAndWrite() {
    return new Promise(function (resolve, reject) {
        horseman.evaluate(function () {
            return document.querySelectorAll("span.DataFormChildDataGridPagerLink+a")[0].text;
        }).then(function (nextPage) {
            console.log(nextPage);
            return horseman
                    .click("span.DataFormChildDataGridPagerLink+a")
                    .then(getListingAndWrite);
        }).then(resolve);
    });
}

horseman
    .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0")
    .open("https://netforum.avectra.com/eweb/DynamicPage.aspx?Site=SLBOR&WebCode=IndResult&FromSearchControl=Yes")
    .waitForSelector("#ctl17__LIST__CONTROL")
    .then(getListingAndWrite)
    .finally(function () {
        horseman.close();
    });
```
And here horseman just will immeditely print 2 2 2 2 2 2

**Comment by awlayton** [comment] 2016-11-04 16:34
`.waitForNextPage()` works for me.

```javascript
var Horseman = require('node-horseman');

var horseman = new Horseman({timeout: 10000});


function getListingAndWrite() {
    return horseman
        .text('span.DataFormChildDataGridPagerLink+a')
        .evaluate(function getText() {
            return $('span.DataFormChildDataGridPagerLink+a')[0].text;
        })
        .log()
        .click('span.DataFormChildDataGridPagerLink+a')
        .waitForNextPage()
        .then(getListingAndWrite);
}

horseman
    .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
    .open('https://netforum.avectra.com/eweb/DynamicPage.aspx?Site=SLBOR&WebCode=IndResult&FromSearchControl=Yes')
    .waitForSelector('#ctl17__LIST__CONTROL')
    .then(getListingAndWrite)
    .close();
```

Output: 2 3 4 ...

**Comment by awlayton** [comment] 2017-03-07 19:05
Closing because I could not reproduce bug.

**Closed by awlayton** 2017-03-07 19:05 UTC
