### ISSUE TITLE
Phantom Process died

### ISSUE THREAD

**Issue by zhuyingda** [johntitus/node-horseman#111] opened 2016-01-16 14:31 UTC
I have met a problem:

```
Unhandled rejection HeadlessError: Phantom Process died
    at ClientRequest.<anonymous> (/Users/zhuyingda/nodejs/veneno/node_modules/node-phantom-simple/node-phantom-simple.js:655:12)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketOnEnd (_http_client.js:288:9)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

I just run this code:

```javascript
var Horseman = require('node-horseman');
var horseman = new Horseman();
horseman
    .userAgent("Mozilla/5.2 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0")
    .on('resourceRequested', function (requestData, networkRequest) {
        if(!/[png|jpg|js|css]$/.test(requestData.url)){
            console.log(requestData.url);
        }
    })
    .open('http://www.zhuyingda.com')
    .log() // prints out the number of results
    .close();
```

I am sure that my network is fine and I can connect this website in my browser.
If I open charles or other vpn program, the problem would be fixed.  I wanna know why?

**Comment by awlayton** [comment] 2016-01-19 16:14
I don't quite follow. Are you say that if you run that code while VPNed it works, but if you run that *same* code while *not* VPNed it gives the above error?

**Comment by zhuyingda** [comment] 2016-01-20 08:04
yeah, I have this problem

**Comment by 0x1mason** [comment] 2016-02-01 22:01
+1 to this error on Windows 7 using example
```js

var Horseman = require('node-horseman');
var horseman = new Horseman();

horseman
  .open('http://www.google.com')
  .type('input[name="q"]', 'github')
  .click("button:contains('Google Search')")
  .waitForNextPage()
  .count("li.g")
  .then(function(numLinks){
	console.log("Number of links: " +numLinks);
	horseman.close();
  });
```

**Comment by 0x1mason** [comment] 2016-02-01 22:11
@zhuyingda  The solution mentioned here worked for me: https://github.com/johntitus/node-horseman/issues/70
```js
var Horseman = require('node-horseman');

var phantomjs = require('phantomjs');

var horseman = new Horseman({phantomPath: phantomjs.path});


horseman
  .open('http://www.google.com')
  .type('input[name="q"]', 'github')
  .click("button:contains('Google Search')")
  .waitForNextPage()
  .count("li.g")
  .then(function(numLinks){
	console.log("Number of links: " +numLinks);
	horseman.close();
  });
```

**Comment by awlayton** [comment] 2016-02-01 22:16
Yeah @0x1mason, horseman does not always find PhantomJS when it is installed by the phantomjs npm module, as mentioned in #101.

**Comment by Yashko** [comment] 2016-03-08 13:57
Any solution?
```
Unhandled rejection HeadlessError: Phantom Process died
    at ClientRequest.<anonymous> (/srv/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:659:12)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickDomainCallback (node.js:381:11)
From previous event:
    at null.<anonymous> (/srv/node_modules/node-horseman/lib/actions.js:51:10)
From previous event:
    at exports.open (/srv/node_modules/node-horseman/lib/actions.js:50:20)
    at null.<anonymous> (/srv/node_modules/node-horseman/lib/index.js:166:22)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
From previous event:
    at Promise.HorsemanPromise.(anonymous function) [as open] (/srv/node_modules/node-horseman/lib/index.js:164:15)
    at Object.exports.data.getBank (/srv/monitoringData/csgoup.js:15:5)
    at /srv/monitoring.js:27:8
    at /srv/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/srv/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/srv/node_modules/async/lib/async.js:209:22)
    at startMonitoring (/srv/monitoring.js:26:8)
    at null._onTimeout (/srv/monitoring.js:36:4)
    at Timer.listOnTimeout (timers.js:119:15)

```

**Comment by johntitus** [comment] 2016-03-08 14:09
@Yashko can you provide an example that causes this error?

**Comment by Yashko** [comment] 2016-03-08 14:26
this code run every ~10 seconds. first 4-5 hours before working okay, but then this error. is there way to catch this so i can reload script?
```
horseman
			.userAgent("Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36")
			.open(this.url)
			.on('consoleMessage', function( msg ){
				horseman
					.waitForSelector(selector)
					.text(selector)
					.then(function(text) {
						var bank = bankFormat(text);
						callback(bank);
					});
			})	
```

**Comment by awlayton** [comment] 2016-03-08 16:58
Can't you just add  a `.catch` to the chain to handle the rejection @Yashko?

**Comment by Yashko** [comment] 2016-03-09 04:50
sorry, i cant find how to do that.

```
horseman
			.userAgent("Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36")
			.open(this.url)
			.catch(function(e) {
				console.log("horseman error: "+e);
			})
```
like this?

**Comment by awlayton** [comment] 2016-03-09 05:03
Yes like that.

**Comment by ultratoast** [comment] 2016-03-14 21:26
So after trying all the fixes listed above and testing several horseman functions I've been able to resolve this issue by removing all calls to horseman.close() from my code. Not sure what the implications of doing this would be if my app was running for a long time (memory leaks, etc).  

Hopefully this helps shed some light on what's happening here.

**Comment by awlayton** [comment] 2016-03-14 21:57
It sounds like you were calling `.close` too early @ultratoast. Unfortunately the `Phantom Process died` message can be cause by many things (including misuse or potential bugs).

**Comment by ultratoast** [comment] 2016-03-14 23:14
Yeah I had a feeling that might be the case, but it wasn't clear given the documentation. Do I not call horseman.close() after completing all actions via horseman? For example in my sequence where i fetch some data via AJAX:

`horseman
  .userAgent(agent)
  .open('https://twitter.com/login?redirect=something')
  .value(login DOM stuff)
  .value(login DOM stuff)
  .click(submit DOM stuff)
  .waitForNextPage()
  .evaluate(function(endpoint){
    function getData() {
      $.ajax({
         url: endpoint
      }).done(function(data){
         window.alert(data)
      })
    }
    return getData()
  },endpoint)
  .on('alert',function(data) {
      return data
  })
  .then(function(data){
    //do stuff with json
  })
.catch(function(e){
  console.log('horseman error: '+e) 
})
.close()
`

**Comment by johntitus** [comment] 2016-03-14 23:33
It's kind of hard to tell since the formatting of your code is broken, but you can't return getData() inside of evaluate. getData is async, and isn't returning until after you've already closed horseman.

Instead of .evalute, use .do()

https://github.com/johntitus/node-horseman#dofn

**Comment by ultratoast** [comment] 2016-03-14 23:57
The trouble is I need to execute that async call from within the phantomjs session. Do() is not giving me access to ajax functions - would I need then to load it (or some other request library) manually?

**Comment by johntitus** [comment] 2016-03-15 00:03
I see now.
@awlayton looks like we need to implement evaluateAsync. However it looks like it returns immediately, so we'd need some kind of wrapper around it, which would be a pain...

http://phantomjs.org/api/webpage/method/evaluate-async.html

**Comment by ultratoast** [comment] 2016-03-15 00:38
I actually got my code working, my issue was that I needed to create a new instance of Horseman inside my function, and then close it at the end. 

If anyone is looking for a quick fix for async calls, the following worked for us (apologies for my formatting skillls):

function pageScraper(){
let horseman = new Horseman()
	horseman
		.userAgent(agent)
		.open(url)
                //Do some DOM stuff
		.waitForNextPage()
		.evaluate(function(endpoint){
			function getData(){
				$.ajax({
					url: endpoint,
					async: false
				}).done(function(data){
					var json = JSON.stringify(data) || 'No Data';
					$('<input id="json"/>').val(json).appendTo('body');
				})
			}
			return getData()
		},endpoint)
		.waitForSelector('#json')
		.value('#json')
		.then(function(data){
			// do stuff with the data,
                       //I have some async fs stuff happening here, at the very end i call this.close()
		})
		.catch(function(e){
			console.log("horseman error: "+e)
			this.close()
		})

}

**Comment by awlayton** [comment] 2016-03-15 02:14
Yeah @ultratoast and @johntitus the `.close` was used correctly, but nothing was waiting for the async started in the `.evaluate`. That lead to the `.close` being "too early".

[v3]: <https://github.com/johntitus/node-horseman/tree/wip-v3>
As for `.evaluateAsync`, the returning immediately makes it not that useful. I have actually already enhanced horseman's `.evaluate` in [v3][] to handle async (either callback or a Promise). See the Readme in [v3][] for details and examples.

**Comment by awlayton** [comment] 2016-03-22 23:11
I am fine with adding `.evaluateAsync` to horseman if you think we should @johntitus. I could also switch my async waiting stuff to be a part of that and make `.evaluate` only sync again. I don't have a terribly strong opinion either way.

**Comment by johntitus** [comment] 2016-03-22 23:41
Just took at look at .evaluate in v3 and I think what you've already done is the right way to go.

**Comment by awlayton** [comment] 2016-04-19 14:54
If the issue is still present in v3, you can reopen this @zhuyingda.

**Closed by awlayton** 2016-04-19 14:54 UTC

**Comment by 0x1mason** [comment] 2016-04-21 14:15
There's some sort of race condition w/ node-phantom-simple on Windows. I've found found the following pattern to be very robust:

```js
var phantomjs = require('phantomjs-prebuilt'),
      Horseman = require('node-horseman'),
      Promise = require('bluebird');

var MAX_RETRIES = 15;

var startHorseman = function (i) {
   i = i || 0;
   var e = null;
   
   return Promise.try(function () {
      console.log('starting');
      return new Horseman({
         phantomPath: phantomjs.path
      });
   })
   
   .catch(function (err) {
      e = err;
   })
   
   .then(function (h) {
      return Promise.delay(2000).then(function () {
         if (!e && h) {
             console.log('returning');
             return Promise.resolve(h);
         }
         
         if (i < MAX_RETRIES) {
            console.log('retrying');
            e = null;
            return startHorseman(++i);
         }
         
         return Promise.reject(new Error('Failed to start PhantomJS.')); 
      });      
   }) 
}

var horseman = startHorseman();

// do stuff

horseman
.close()
.catch(function(e) { 
   console.warn("Error closing PhantomJS: " + e);
   console.warn(e.stack);   
})  
```

Could be cleaner, but you get the gist.

**Comment by awlayton** [comment] 2016-04-21 15:14
What are you claiming is wrong @0x1mason? Are you getting an error?

When I run your code I get an error from `horseman.close()`, but that is because your `horseman` variable is a `Promise` and not a `Horseman` instance. Everything else does what I would expect.

**Comment by 0x1mason** [comment] 2016-04-21 17:27
There appears to be a race condition that produces the `headless` errors. I
posted my snippet if anyone else has an issue since it resolved the issue
for me.

**Comment by 0x1mason** [comment] 2016-04-21 17:28
Which is to say, nothing's wrong really :) sorry if I was unclear.

**Comment by andrerpena** [comment] 2016-08-28 20:07
I was having the exact problem since 11:00h. It is 17:00h now my time.
It turns out @ultratoast was right and saved my day. I just removed all calls to `close()` and it suddenly worked. What I'm doing now is that I'm sharing a single Horseman instance and closing it at the end.
